# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9b13bc47ec1697c57605694eee59f52e23fcfec84f7bd6154999dfb256c02cb5a05b6e0eba36118f959f92524286a8f3db25bd4c53c2e4a25ccf386aa01390

test:
  secret_key_base: c7541679352aa00bced40cdfe2b005b20a30a09296081b343a64d9c784fdef3910e7b0945e8d6901992b63e8f9d9e8e005d2bff32c09e4dc070e558d9ad51fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
